### ISSUE TITLE
Blank site when i login into the Webinterface

### ISSUE THREAD

**Issue by LiebesWavezLP** [zekroTJA/shinpuru#328]
### Type

Breaking Issue

### Instances

- [ ] Canary
- [ ] Stable
- [X] Self-Hosted

### Description

Im not able to login into the webinterface, because when i try to login after a succesfull auth im stuck at the webpath "/api/auth/oauthcallback?code=" and im not logged in, in the webinterface.

(i removed the code for this report)

### Steps to reproduce

1. go to your bots webinterface
2. press on the login button
3. authorize the login 

### Attachments

I got no errors or anything else, just only a blank site
![bugreport-shinpu-web](https://user-images.githubusercontent.com/33105443/148682518-f2920baf-230e-4071-99c6-90947e07cecf.png)

**Comment by zekroTJA** [comment]
Hm, that's weird. 

Do you use the Docker image or the binaries from the release page?

Also, could you please repeat the login process with the developer tools of the browser open?  
You can open them by pressing <kbd>F12</kbd> or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>. After that, log in until you are stuck again on that blank page. Now, please go to the `Network` tab in the developer tools. After that, if there are any failed (maked red) requests, please click on each and provide a screen shot of them like shown in the example below. And please don't forget to hide any potential credentials the the screenshot like cookie headers or token query parameters. ;)

![image](https://user-images.githubusercontent.com/16734205/148685599-badec127-fc10-46cc-ad29-c5fecd1c7dff.png)

**Comment by LiebesWavezLP** [comment]
Hi,
I use the the binaries. Version 1.27.0.

**Comment by zekroTJA** [comment]
This is actually really odd, because this handler should never return a blank `200 OK`.

I tried to reproduce this by downloading the binaries (release 1.27.0) and running them on a completely clean MariaDB as well as Redis instance and was not able to reproduce this behavior. 

Either there is an issue with your configuration or with your routing / rev proxy environment.

For my testing, I've used the following config:
```yml
configVersionPleaseDoNotChange: 6
codeexec:
  ranna:
    apiversion: v1
    endpoint: 'https://public.ranna.zekro.de'
    token: ''
  type: ranna
database:
  mysql:
    database: 'shinpuru'
    host: 'localhost:3306'
    password: 'dev'
    user: 'root'
  type: mysql
cache:
  redis:
    addr: "localhost:6379"
    type: 0
  cachedatabase: true
discord:
  clientid: '911603978758914089'
  clientsecret: '***'
  generalprefix: ;;
  ownerid: '221905671296253953'
  token: '***'
  disabledcommands:
logging:
  commandlogging: true
  loglevel: 5
permissions:
  defaultadminrules:
    - +sp.guild.*
    - +sp.etc.*
    - +sp.chat.*
  defaultuserrules:
    - +sp.etc.*
    - +sp.chat.*
schedules:
storage:
  minio:
    accesskey: 'dev-access-key'
    accesssecret: 'dev-secret-key'
    endpoint: 'localhost:9000'
    location: us-east-1
    secure: false
  type: minio
twitchapp:
  clientid: "***"
  clientsecret: "***"
webserver:
  addr: :8080
  apitokenkey: "***"
  enabled: true
  landingpage:
    showlocalinvite: true
    showpublicinvites: true
  publicaddr: http://localhost:8080
  captcha:
    sitekey: "20000000-ffff-ffff-ffff-000000000002"
    secretkey: "0x0000000000000000000000000000000000000000"
metrics:
  enable: true
  addr: ":9091"
```

Could you please provide your config (with the secrets removed ofc) just so that I can have a look over it?

**Comment by LiebesWavezLP** [comment]
This is my config!
```yml
configVersionPleaseDoNotChange: 6
discord:
  token: "xxx"
  generalprefix: ";;"
  ownerid: "312998964465238018"
  clientid: "925204349028819026"
  clientsecret: "xxx"
   globalcommandratelimit:
    burst: 1
    limitseconds: 10
permissions:
  defaultuserrules:
  - +sp.etc.*
  - +sp.chat.*
  defaultadminrules:
  - +sp.guild.*
  - +sp.etc.*
  - +sp.chat.*

database:
  type: "mysql"
  mysql:
    host: "localhost"
    user: "database_user"
    password: "database_password"
    database: "database"
cache:
  redis:
    addr: "localhost:6379"
    password: "redis_password"
    type: 0
  cachedatabase: true
logging:
  commandlogging: true
  loglevel: 4
storage:
  type: "file"
minio:
    endpoint: "minio.exmaple.com"
    accesskey: "my_minio_access_key"
    accesssecret: "my_minio_access_secret"
    location: "us-east-1"
    secure: false
  file:
    location: /home/dcbot/data
webserver:
  enabled: true
  addr: 0.0.0.0:80
  tls:
    enabled: false
    cert: "/etc/cert/mycert.pem"
    key: "/etc/cert/mykey.pem"
  publicaddr: "http://api.theuwuclan.de"
  debugpublicaddr: "http://localhost:8081"
  ratelimit:
    enabled: true
    burst: 50
    limitseconds: 3
twitchapp:
  clientid: "f34eqnjavd5so30yoivbu9ls5pjfek"
  clientsecret: "xxx"
metrics:
  enable: true
  addr: ":9091"
schedules:
  guildbackups:        '0 0 6,18 * * *'
  refreshtokencleanup: '0 0 5 * * *'
```
